version: '3'
services:
  #  To start replica mode please use `docker-init.sh`
  postgres_master:
    container_name: postgres_master
    image: postgres:14.5
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./data-slave-1:/var/lib/postgresql/data-slave-1
      - ./data-slave-2:/var/lib/postgresql/data-slave-2
      - ./init-script/config/postgres.conf:/etc/postgresql/postgresql.conf
      - ./init-script/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./init-script:/etc/postgresql/init-script
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql


  postgres_slave_1:
    container_name: postgres_slave_1
    image: postgres:14.5
    restart: always
    volumes:
      - ./data-slave-1:/var/lib/postgresql/data
      - ./config-1/postgres.conf:/etc/postgresql/postgresql.conf
      - ./config-1/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql


  postgres_slave_2:
    container_name: postgres_slave_2
    image: postgres:14.5
    restart: always
    volumes:
      - ./data-slave-2:/var/lib/postgresql/data
      - ./config-2/postgres.conf:/etc/postgresql/postgresql.conf
      - ./config-2/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "127.0.0.1:5434:5432"
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
